services:
  nginxTest:
    container_name: frontend
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./www:/usr/share/nginx/html

  goapp:
    container_name: backend-go
    build: goapp/
    ports:
      - 8081:8081
    volumes:
      - ./goapp:/go/src/app

  mysql:
    container_name: mysql-db
    build: db-config/
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db-config:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imersaoFC11
      MYSQL_PASSWORD: root
